// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/DaneshBonyan/Aside.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CardImageCenter: typeof import('./src/components/Shared/CardImageCenter.vue')['default']
    CardWithImageTop: typeof import('./src/components/Shared/CardWithImageTop.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Course: typeof import('./src/components/Course.vue')['default']
    CustomArrows: typeof import('./src/components/Shared/CustomArrows.vue')['default']
    CustomCarousel: typeof import('./src/components/Shared/CustomCarousel.vue')['default']
    CustomNavigation: typeof import('./src/components/Shared/CustomNavigation.vue')['default']
    FirstSection: typeof import('./src/components/RoshdCenter/FirstSection.vue')['default']
    FlexBetween: typeof import('./src/components/RoshdCenter/FlexBetween.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomeFirstCardContainer: typeof import('./src/components/HomePage/HomeFirstCardContainer.vue')['default']
    HomeSecondContainer: typeof import('./src/components/HomePage/HomeSecondContainer.vue')['default']
    HomeThirdContainer: typeof import('./src/components/HomePage/HomeThirdContainer.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/DaneshBonyan/SearchComponent.vue')['default']
    TextWithLightBottomBorder: typeof import('./src/components/Shared/TextWithLightBottomBorder.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
